### ISSUE TITLE
error upon entering toolbox on a fresh install.

### ISSUE THREAD

**Issue by superuser-miguel** [palazzem/archlinux-toolbox#5]
`toolbox create -i docker.io/palazzem/archlinux-toolbox:latest -c archlinux-toolbox`
Image required to create toolbox container.
Download docker.io/palazzem/archlinux-toolbox:latest (500MB)? [y/N]: y
Creating container archlinux-toolbox: / Created container: archlinux-toolbox
Enter with: toolbox enter archlinux-toolbox
`toolbox enter archlinux-toolbox`
WARNING: libcap needs an update (cap=40 should have a name).
bash: PROMPT_COMMAND: line 0: syntax error near unexpected token `;'
bash: PROMPT_COMMAND: line 0: ` ; printf "\033]0;%s@%s:%s\007" "${USER}" "${HOSTNAME%%.*}" "${PWD/#$HOME/\~}"'

**Comment by palazzem** [comment]
@superuser-miguel this issue should be addressed. To try it again, remove or untag `docker.io/palazzem/archlinux-toolbox:latest` image, so that it will download the updated image.

Thanks for reporting the issue!
